# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 FINE Association <su@fa.org.tr>

edition = "2024"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
